# Generated by Django 5.0.2 on 2024-08-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='level',
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='realty.floor'),
        ),
    ]
